### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by cherifVN** [kobaltcore/renpy-translate#1]
@kobaltcore Hello i like your project so I have some question: 
firstly, will there be a next version of this code or has it been abandoned ?
secondly i am working on a new version of this code aimed at changing the Google API which is paid into a completely free API by therefore adapting certain parts. I also fix some problems I encountered with this program for example it translates variables in [ ] and other problems.
So I would like to have your opinion on this.

**Comment by kobaltcore** [comment]
Thanks for the feedback! I don't have any immediate plans to return to it, though the option's always there, I suppose. The code is MIT licensed, so you're free to do whatever you like with it, I don't really mind.

The whole variable/formatting stuff I am aware of, for my use case back then it was never really an issue, so I didn't bother to build a full parser for the strings to resolve those problems properly. Afaik Ren'Py has some built-in functions that can strip tags from dialogue/narration, so if I were to implement something like that I'd probably start there. However, if you want to do so (maybe send a PR or just maintain a fork of this project instead), then by all means, go ahead.

I'm also potentially open on working on this together, so if you start with a PR we could go from there if you so desire. Otherwise, consider this your carte blanche to do whatever you feel like.

**Comment by kobaltcore** [comment]
Closing this since no further comments have been made for a week now.
